---
- name: Get Service Status
  hosts: all


  tasks:
    - name: Check the service status
      ansible.builtin.shell: "service cron status | grep -i running"
      register: service_state

    - name: Display the service status
      debug:
        var: service_state.stdout 
