---
- name: Get Service Status
  hosts: all
  vars:
    ansible_user: 'ansible'
    ansible_password: 'root1234@'


  tasks:
    - name: Check the service status
      ansible.builtin.shell: "sudo service cron status "
      register: service_state

    - name: Display the service status
      debug:
        var: service_state.stdout 
