---
- name: Stop Service
  hosts: all
  become: true
  become_user: "{{ANSIBLE_SVCACCOUNT}}"
  become_method: community.general.sudosu

  vars:
    ansible_user: '{{ lookup("env", "ANSIBLE_USER") }}'
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_remote_tmp: /tmp

  tasks:
    - name: Stopping the service
      ansible.builtin.shell: "sudo systemctl stop {{SERVICE}}"
       
    - name: Cheking Service Status
      ansible.builtin.shell: sudo systemctl status "{{SERVICE}}" | grep -i active
      register: service_status

    - name: Display the service status
      debug:
        var: service_status.stdout