---
- name: Get Service Status
  hosts: all
  become: true
  become_user: "{{SVCACCOUNT}}"
  become_method: community.general.sudosu
  vars:
    ansible_user: '{{ lookup("env", "ANSIBLE_USER") }}'
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_become_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_remote_tmp: '/tmp'
    # service: '{{ lookup("env", "SERVICE") }}'

  tasks:
    - name: Check the service status
      ansible.builtin.systemd:
        name: "{{SERVICE}}"
          # state: status
      register: service_status

    - name: Display the service status
      debug:
        var: service_status
